### ISSUE TITLE
suggestion: don't use canvas anymore

### ISSUE THREAD

**Issue by jariz** [ivansevillaa/use-next-blurhash#10]
So I found this great gist that can decode a blurhash directly into a data url, no canvas required:
https://gist.github.com/mattiaz9/53cb67040fa135cb395b1d015a200aff

Creating a canvas element every time to decode the blurhash into a data url adds quite a bit of overhead, additionally, on the node side it requires you to use the entire `canvas` package (which is a rather large dependency because it needs to be able to do everything canvas can)

**Comment by ivansevillaa** [comment]
Thank you that's great!!

Do you wanna create a PR?

**Comment by ivansevillaa** [comment]
Workin on: https://github.com/ivansevillaa/use-next-blurhash/pull/11 thanks @Vatiba for the help ❤️
